export type NodeCategory = 'text' | 'image' | 'video' | 'edit' | 'mask' | 'helper' | 'output'

export interface NodeInfo {
  type: string
  label: string
  category: NodeCategory
  description: string
  simpleExplanation: string
  inputs: string[]
  outputs: string[]
  color: string
}

export const NODE_COLORS: Record<NodeCategory, string> = {
  text: '#a78bfa',
  image: '#00c896',
  video: '#ff4d6d',
  edit: '#38bdf8',
  mask: '#a3e635',
  helper: '#fb923c',
  output: '#fbbf24',
}

export const NODE_CATALOG: NodeInfo[] = [
  // ── TEXT / PROMPT ──────────────────────────────────────────
  {
    type: 'promptNode',
    label: 'Prompt',
    category: 'text',
    color: '#a78bfa',
    description: 'A basic text input for your creative prompt.',
    simpleExplanation: '✍️ Type what you want to create here. Like telling the AI "make me a sunset on a beach" — it\'s the starting point of everything!',
    inputs: [],
    outputs: ['text'],
  },
  {
    type: 'promptEnhancerNode',
    label: 'Prompt Enhancer',
    category: 'text',
    color: '#a78bfa',
    description: 'Automatically improves your prompt using AI.',
    simpleExplanation: '✨ Your prompt goes in, a BETTER prompt comes out. The AI rewrites it with more detail so your image or video looks amazing. Like a spell-checker but for creativity!',
    inputs: ['text'],
    outputs: ['text'],
  },
  {
    type: 'promptConcatNode',
    label: 'Prompt Combiner',
    category: 'text',
    color: '#a78bfa',
    description: 'Combines multiple prompts into one.',
    simpleExplanation: '🔗 Connect two or more prompts and this merges them into one big prompt. Useful when you have different ideas you want to blend together.',
    inputs: ['text', 'text'],
    outputs: ['text'],
  },
  {
    type: 'directorPromptNode',
    label: 'Director Formula',
    category: 'text',
    color: '#a78bfa',
    description: 'Structured image-prompt builder using the SHOT + LENS + LIGHT + TEXTURE + COMPOSITION + STYLE REF formula.',
    simpleExplanation: 'Fill in the 7 fields like a creative director writing a brief — shot type, lens, lighting, materials, composition, style reference, vision. The node assembles a director-grade prompt that you wire into any Text → Image / Compositor / Reference Sheet. Encodes cinematography vocab so you do not need to remember every term.',
    inputs: [],
    outputs: ['text'],
  },
  {
    type: 'imageDescriberNode',
    label: 'Image Describer',
    category: 'text',
    color: '#a78bfa',
    description: 'Analyzes an image and generates a detailed prompt from it.',
    simpleExplanation: '🔍 Give it a photo and it tells you exactly what\'s in it as a detailed prompt. Perfect for recreating a style or analyzing what makes an image look the way it does!',
    inputs: ['image'],
    outputs: ['text'],
  },
  {
    type: 'imageToJsonNode',
    label: 'Image → JSON',
    category: 'text',
    color: '#a78bfa',
    description: 'Analyses 1–5 images with a vision LLM and outputs one strict JSON description covering all of them.',
    simpleExplanation: 'Feed in up to 5 photos of the same subject. Get out one structured JSON spec of everything visible — brands, materials, colours, signage text. Wire the JSON into any downstream text input to lock identity/location for image gen.',
    inputs: ['image1', 'image2', 'image3', 'image4', 'image5'],
    outputs: ['text'],
  },
  {
    type: 'videoDescriberNode',
    label: 'Video Describer',
    category: 'text',
    color: '#a78bfa',
    description: 'Analyzes a video and generates a detailed prompt from it.',
    simpleExplanation: '🎬 Same as Image Describer but for videos. It watches your video and writes out what\'s happening so you can recreate or remix it.',
    inputs: ['video'],
    outputs: ['text'],
  },
  {
    type: 'audioTranscriberNode',
    label: 'Audio Transcriber',
    category: 'text',
    color: '#a78bfa',
    description: 'Transcribes spoken audio into text using Whisper or Gemini.',
    simpleExplanation: 'Listens to your uploaded audio and writes out the spoken script as text. Useful for feeding the actual words being said into a video model so it can time camera cuts and gestures to match.',
    inputs: ['audio'],
    outputs: ['text'],
  },
  {
    type: 'ttsNode',
    label: 'Text → Speech',
    category: 'text',
    color: '#a78bfa',
    description: 'Generates voice audio from a text script using OpenAI, Gemini, MiniMax, or ElevenLabs voices.',
    simpleExplanation: 'Type a script (or wire one in), pick a voice, optionally tell it the style (cheerful, calm, conspiratorial), and it generates the audio. For ElevenLabs free tier, wire a Voice Cloner node into the voiceId input. Pipe the output into Lip Sync to make a video character say it.',
    inputs: ['text', 'voiceId'],
    outputs: ['audio'],
  },
  {
    type: 'voiceClonerNode',
    label: 'Voice Cloner',
    category: 'text',
    color: '#a78bfa',
    description: 'Creates an ElevenLabs cloned voice from a 30+ second audio sample. Outputs a voice_id for the TTS node.',
    simpleExplanation: 'Wire in an audio file (30+ sec of clean speech — your own voice, a podcast clip, anything), give it a name, click Clone. ElevenLabs trains an instant voice clone and returns a voice_id. Wire that voiceId into a Text → Speech node and every TTS call uses that voice. Free tier compatible — clone YOUR voice once, use it forever.',
    inputs: ['audio'],
    outputs: ['voiceId'],
  },
  {
    type: 'llmNode',
    label: 'Run Any LLM',
    category: 'text',
    color: '#a78bfa',
    description: 'Send text and image to any AI language model and get a text response.',
    simpleExplanation: '🤖 Talk to any AI brain (ChatGPT, Gemini, etc.) directly inside your workflow. Ask it questions, get descriptions, or have it write prompts for you!',
    inputs: ['text', 'image'],
    outputs: ['text'],
  },

  // ── IMAGE GENERATE ─────────────────────────────────────────
  {
    type: 'textToImageNode',
    label: 'Text → Image',
    category: 'image',
    color: '#00c896',
    description: 'Generates an image from a text prompt.',
    simpleExplanation: '🖼️ Type a description and it draws a picture for you! Choose from different AI models like DALL-E, Flux, or Imagen — each has its own style. This is probably the most fun node!',
    inputs: ['text'],
    outputs: ['image'],
  },
  {
    type: 'imageToImageNode',
    label: 'Image → Image',
    category: 'image',
    color: '#00c896',
    description: 'Transforms an existing image using a prompt.',
    simpleExplanation: '🎨 Give it a photo + a description and it transforms the photo. Like "make this photo look like an oil painting" or "change the season to winter."',
    inputs: ['image', 'text'],
    outputs: ['image'],
  },
  {
    type: 'upscaleNode',
    label: 'Upscale',
    category: 'image',
    color: '#00c896',
    description: 'Increases image resolution and adds fine detail.',
    simpleExplanation: '🔬 Makes small or blurry images bigger and sharper. It doesn\'t just stretch — it actually invents new detail. Turn a tiny 512px image into a crisp 4K masterpiece!',
    inputs: ['image'],
    outputs: ['image'],
  },
  {
    type: 'bgRemoveNode',
    label: 'Remove Background',
    category: 'image',
    color: '#00c896',
    description: 'Removes the background from an image automatically.',
    simpleExplanation: '✂️ Cuts out the background of any photo automatically. Your subject stays, the background disappears. Great for product photos or placing people into new scenes!',
    inputs: ['image'],
    outputs: ['image'],
  },
  {
    type: 'relightNode',
    label: 'Relight',
    category: 'image',
    color: '#00c896',
    description: 'Changes the lighting in an image.',
    simpleExplanation: '💡 Changes where the light is coming from in a photo. Make a daytime photo look like it was shot at sunset, or add dramatic studio lighting — without a studio!',
    inputs: ['image', 'text'],
    outputs: ['image'],
  },
  {
    type: 'inpaintNode',
    label: 'Inpaint',
    category: 'image',
    color: '#00c896',
    description: 'Fills in or replaces a selected area of an image.',
    simpleExplanation: '🖌️ Paint over something you don\'t want and the AI fills it in naturally. Remove a person from a photo, erase a logo, or replace the sky — it blends in seamlessly!',
    inputs: ['image', 'mask', 'text'],
    outputs: ['image'],
  },
  {
    type: 'outpaintNode',
    label: 'Outpaint',
    category: 'image',
    color: '#00c896',
    description: 'Extends an image beyond its original borders.',
    simpleExplanation: '📐 Makes your image wider or taller by generating what would be outside the frame. Like zooming out from a photo — the AI imagines what\'s beyond the edges!',
    inputs: ['image', 'text'],
    outputs: ['image'],
  },
  {
    type: 'faceSwapNode',
    label: 'Face Swap',
    category: 'image',
    color: '#00c896',
    description: 'Swaps a face from one image onto another.',
    simpleExplanation: '😄 Put your face (or anyone\'s face) onto a different body or scene. It handles skin tone, lighting and angle automatically so it looks realistic!',
    inputs: ['image', 'image'],
    outputs: ['image'],
  },
  {
    type: 'objectRemoveNode',
    label: 'Object Remove',
    category: 'image',
    color: '#00c896',
    description: 'Removes unwanted objects from an image.',
    simpleExplanation: '🗑️ Point at anything in your photo and poof — it\'s gone! The AI fills in what the background would look like without it. Remove tourists from travel photos, wires from product shots, anything!',
    inputs: ['image', 'mask'],
    outputs: ['image'],
  },
  {
    type: 'outfitChangeNode',
    label: 'Outfit Change',
    category: 'image',
    color: '#00c896',
    description: 'Changes clothing in an image using AI.',
    simpleExplanation: '👗 Virtually try on different outfits! Describe what clothing you want and the AI puts it on the person in the photo. Great for fashion, e-commerce, or just fun!',
    inputs: ['image', 'text'],
    outputs: ['image'],
  },
  {
    type: 'compositorNode',
    label: 'Compositor',
    category: 'image',
    color: '#00c896',
    description: 'Composites a subject image into a scene image with a prompt. Optional JSON spec inputs lock identity / location.',
    simpleExplanation: 'Drop a SUBJECT image and a SCENE image. Write a prompt describing how to combine them. Optionally wire Image→JSON specs into subject-spec / scene-spec to give the model text anchors that lock identity and location — best for "put this exact person in this exact place".',
    inputs: ['subject', 'scene', 'text', 'subjectJson', 'sceneJson'],
    outputs: ['image'],
  },
  {
    type: 'referenceSheetNode',
    label: 'Reference Sheet',
    category: 'image',
    color: '#00c896',
    description: 'Multi-reference image stage — wire up to 6 photos of the same person, place, or product to lock identity / location.',
    simpleExplanation: 'Wire multiple photos of the SAME thing (person, place, product) into the ref inputs. The model uses all of them as identity anchors. Way better than asking it to imagine angles from a single photo.',
    inputs: ['ref1', 'ref2', 'ref3', 'ref4', 'ref5', 'ref6', 'text'],
    outputs: ['image'],
  },
  {
    type: 'characterBoardNode',
    label: 'Character Board',
    category: 'image',
    color: '#00c896',
    description: 'Generates a full character reference board (8 headshots + 4 full-body angles + detail callouts + swatches) from 1-5 photos of a person. Anti-fake realism + director-formula lighting baked.',
    simpleExplanation: 'Drop photos of a person. Out comes a studio model board — head expressions, four full-body angles, hand/eye/shoulder close-ups, fabric and skin swatches. Pore-level texture, no plastic skin, ultra realism baked. Wire Image→JSON in for tighter identity lock.',
    inputs: ['ref1', 'ref2', 'ref3', 'ref4', 'ref5', 'subjectJson', 'text'],
    outputs: ['image'],
  },
  {
    type: 'locationBoardNode',
    label: 'Location Board',
    category: 'image',
    color: '#00c896',
    description: 'Generates a full location reference board (exterior angles, time-of-day variants, signage close-ups, material swatches) from 1-5 photos of a place.',
    simpleExplanation: 'Drop photos of a storefront, room, or building. Out comes a location board — exterior angles, time-of-day variants (golden / midday / blue / night), signage close-ups, material swatches. Director-formula lens + 4-facet lighting per panel.',
    inputs: ['ref1', 'ref2', 'ref3', 'ref4', 'ref5', 'subjectJson', 'text'],
    outputs: ['image'],
  },
  {
    type: 'productBoardNode',
    label: 'Product Board',
    category: 'image',
    color: '#00c896',
    description: 'Generates a full product reference board (hero angles, in-hand shots, detail callouts, colourways) from 1-5 photos of a product.',
    simpleExplanation: 'Drop photos of a product. Out comes a spec-board — hero angles, in-hand shots, brand-mark and material close-ups, colourway swatches. Macro-detail lens + softbox-fill-rim lighting baked per panel.',
    inputs: ['ref1', 'ref2', 'ref3', 'ref4', 'ref5', 'subjectJson', 'text'],
    outputs: ['image'],
  },
  {
    type: 'bRollBoardNode',
    label: 'B-roll Board',
    category: 'image',
    color: '#00c896',
    description: 'Generates a B-roll reference board — supporting cutaway frames (hands, atmosphere, environment details, lifestyle moments) that share the same colour grade and visual language as the main shot.',
    simpleExplanation: 'Drop photos of your scene / subject / product. Out comes a board of cutaway-style frames — hands working, atmosphere details, environment beats, lifestyle moments — all tied together by one colour grade and lighting era. Use for video editing or campaign asset libraries.',
    inputs: ['ref1', 'ref2', 'ref3', 'ref4', 'ref5', 'subjectJson', 'text'],
    outputs: ['image'],
  },
  {
    type: 'storyboardNode',
    label: 'Storyboard',
    category: 'image',
    color: '#00c896',
    description: 'Generates a sequential storyboard — 6-9 numbered panels showing a narrative beat-by-beat with shot type and action labels.',
    simpleExplanation: 'Drop photos of your scene / character / setting. Out comes a 6-9 panel storyboard — each panel labelled with shot type (ECU / CU / MS / FS / LS) and the action happening. Use to plan a video shoot or pitch a sequence.',
    inputs: ['ref1', 'ref2', 'ref3', 'ref4', 'ref5', 'subjectJson', 'text'],
    outputs: ['image'],
  },
  {
    type: 'mascotBoardNode',
    label: 'Mascot Board',
    category: 'image',
    color: '#00c896',
    description: 'Generates a brand-mascot reference board — multiple expressions, poses, scale references, brand-colour palette swatches.',
    simpleExplanation: 'Drop photos / concept art of a brand mascot. Out comes a mascot bible — 6 expressions, 6 poses, orthographic views (front / side / back / 3-4), brand colour palette, material swatches. Locks the mascot for consistent reuse across campaigns.',
    inputs: ['ref1', 'ref2', 'ref3', 'ref4', 'ref5', 'subjectJson', 'text'],
    outputs: ['image'],
  },
  {
    type: 'creatureBoardNode',
    label: 'Creature Board',
    category: 'image',
    color: '#00c896',
    description: 'Generates a creature / monster / animal reference board — orthographic views, detail callouts, scale silhouette, material swatches (skin / fur / scales / feathers).',
    simpleExplanation: 'Drop photos / concept art of a creature. Out comes a concept-art board — front / 3-4 / side / back / top views, face and limb detail callouts, scale silhouette next to a human, material swatches for skin / fur / scales / feathers. Locks the creature for consistent appearances.',
    inputs: ['ref1', 'ref2', 'ref3', 'ref4', 'ref5', 'subjectJson', 'text'],
    outputs: ['image'],
  },

  // ── VIDEO GENERATE ─────────────────────────────────────────
  {
    type: 'textToVideoNode',
    label: 'Text → Video',
    category: 'video',
    color: '#ff4d6d',
    description: 'Generates a video from a text description.',
    simpleExplanation: '🎥 Type what you want to see and it creates a video! "A cat surfing a wave at sunset" — done. Choose from Kling, Veo3, Wan, Sora and more. Each model has different styles!',
    inputs: ['text'],
    outputs: ['video'],
  },
  {
    type: 'imageToVideoNode',
    label: 'Image → Video',
    category: 'video',
    color: '#ff4d6d',
    description: 'Animates a still image into a video.',
    simpleExplanation: '🌊 Bring a photo to life! Give it your image and it creates a short video of it moving — waves crashing, hair blowing, eyes blinking. Like a magical moving portrait!',
    inputs: ['image', 'text'],
    outputs: ['video'],
  },
  {
    type: 'videoToVideoNode',
    label: 'Video → Video',
    category: 'video',
    color: '#ff4d6d',
    description: 'Transforms or re-styles an existing video.',
    simpleExplanation: '🔄 Transform a video\'s look completely. "Make this video look like an anime cartoon" or "make it look like it was filmed in the 1970s." Same motion, totally new style!',
    inputs: ['video', 'text'],
    outputs: ['video'],
  },
  {
    type: 'lipSyncNode',
    label: 'Lip Sync',
    category: 'video',
    color: '#ff4d6d',
    description: 'Makes a person in a video speak with your audio.',
    simpleExplanation: '🎤 Upload a video of a person and an audio clip — it animates their lips to match the audio! Make anyone say anything. Great for ads, content, or fun!',
    inputs: ['video', 'audio'],
    outputs: ['video'],
  },
  {
    type: 'videoUpscaleNode',
    label: 'Video Upscale',
    category: 'video',
    color: '#ff4d6d',
    description: 'Improves video quality and resolution.',
    simpleExplanation: '📺 Makes blurry or low-quality videos look sharp and crisp. Like having a time machine to remaster old footage — the AI adds detail that was never there!',
    inputs: ['video'],
    outputs: ['video'],
  },
  {
    type: 'speechToVideoNode',
    label: 'Speech → Video',
    category: 'video',
    color: '#ff4d6d',
    description: 'Creates a talking video from an image and speech audio.',
    simpleExplanation: '🗣️ Take a portrait photo, add a voice recording, and get a video of that person speaking! Perfect for creating AI avatars or making photos "talk."',
    inputs: ['image', 'audio'],
    outputs: ['video'],
  },

  // ── EDITING TOOLS ──────────────────────────────────────────
  {
    type: 'compositorNode',
    label: 'Compositor',
    category: 'edit',
    color: '#38bdf8',
    description: 'Layers multiple images or videos together with blend modes.',
    simpleExplanation: '🎞️ Stack images and videos on top of each other like layers in Photoshop. Drag, resize and position elements exactly where you want. Add blend effects like "multiply" or "screen." This is your editing studio!',
    inputs: ['image', 'video'],
    outputs: ['image', 'video'],
  },
  {
    type: 'cropNode',
    label: 'Crop',
    category: 'edit',
    color: '#38bdf8',
    description: 'Crops and resizes an image or video.',
    simpleExplanation: '✂️ Cut your image or video to a specific size or shape. Choose preset ratios like 16:9 for YouTube, 9:16 for TikTok, or 1:1 for Instagram. No AI needed — instant!',
    inputs: ['image'],
    outputs: ['image'],
  },
  {
    type: 'blurNode',
    label: 'Blur',
    category: 'edit',
    color: '#38bdf8',
    description: 'Applies a blur effect to an image or video.',
    simpleExplanation: '🌫️ Makes things fuzzy! Use it to blur backgrounds, censor things, or create a dreamy soft focus effect. Slide to control how blurry it gets.',
    inputs: ['image'],
    outputs: ['image'],
  },
  {
    type: 'levelsNode',
    label: 'Levels',
    category: 'edit',
    color: '#38bdf8',
    description: 'Adjusts brightness, contrast and tone.',
    simpleExplanation: '☀️ Make your image brighter, darker, or more contrasty. It\'s like the basic sliders in your phone\'s photo editor but built right into your workflow!',
    inputs: ['image'],
    outputs: ['image'],
  },
  {
    type: 'invertNode',
    label: 'Invert',
    category: 'edit',
    color: '#38bdf8',
    description: 'Inverts the colors of an image.',
    simpleExplanation: '🔄 Flips all colors to their opposite — like a photo negative. Black becomes white, white becomes black. Very useful for flipping masks!',
    inputs: ['image'],
    outputs: ['image'],
  },
  {
    type: 'extractFrameNode',
    label: 'Extract Frame',
    category: 'edit',
    color: '#38bdf8',
    description: 'Pulls a specific frame out of a video as an image.',
    simpleExplanation: '📷 Grab any single frame from a video and save it as a still image. Pick the exact moment you want — frame by frame!',
    inputs: ['video'],
    outputs: ['image'],
  },
  {
    type: 'painterNode',
    label: 'Painter',
    category: 'edit',
    color: '#38bdf8',
    description: 'Draw or paint directly on a canvas to create masks or sketches.',
    simpleExplanation: '🖌️ Draw directly on your image with a brush! Use it to paint masks (selecting areas to edit) or create rough sketches that the AI can turn into full images.',
    inputs: ['image'],
    outputs: ['image', 'mask'],
  },

  // ── MATTE / MASK ───────────────────────────────────────────
  {
    type: 'maskExtractorNode',
    label: 'Mask Extractor',
    category: 'mask',
    color: '#a3e635',
    description: 'Automatically selects parts of an image to create a mask.',
    simpleExplanation: '🎯 Click on objects in your image and it automatically traces around them to create a precise selection. Like magic scissors that cut out exactly what you want!',
    inputs: ['image'],
    outputs: ['mask'],
  },
  {
    type: 'maskByTextNode',
    label: 'Mask by Text',
    category: 'mask',
    color: '#a3e635',
    description: 'Creates a mask by describing what to select in text.',
    simpleExplanation: '💬 Just describe what you want to select — "the person\'s hair" or "the car" — and it draws the selection for you automatically. No clicking needed!',
    inputs: ['image', 'text'],
    outputs: ['mask'],
  },
  {
    type: 'matteGrowShrinkNode',
    label: 'Matte Grow/Shrink',
    category: 'mask',
    color: '#a3e635',
    description: 'Expands or shrinks a mask edge.',
    simpleExplanation: '⬆️⬇️ Makes your selection slightly bigger or smaller. Use this to clean up rough edges — expand to include more, shrink to exclude background bits.',
    inputs: ['mask'],
    outputs: ['mask'],
  },
  {
    type: 'mergeAlphaNode',
    label: 'Merge Alpha',
    category: 'mask',
    color: '#a3e635',
    description: 'Applies a mask to an image to create transparency.',
    simpleExplanation: '🔲 Takes your image and your mask and combines them — the masked area becomes transparent (see-through). This is how you get cutout images with no background!',
    inputs: ['image', 'mask'],
    outputs: ['image'],
  },
  {
    type: 'videoMatteNode',
    label: 'Video Matte',
    category: 'mask',
    color: '#a3e635',
    description: 'Extracts a matte/mask from a video.',
    simpleExplanation: '🎭 Does the same magic as Mask Extractor but on videos. Tracks and extracts a subject through the whole video — like removing the background from every single frame automatically!',
    inputs: ['video'],
    outputs: ['mask'],
  },

  // ── INTEGRATIONS ───────────────────────────────────────────
  {
    type: 'figmaImportNode',
    label: 'Import from Figma',
    category: 'helper',
    color: '#8B7250',
    description: 'Paste a Figma frame URL to pull it into the canvas as an image.',
    simpleExplanation: 'Copy a frame URL from Figma (right-click → Copy link to selection) and paste it here. Pulls the frame in as an image you can feed downstream.',
    inputs: [],
    outputs: ['image'],
  },
  {
    type: 'urlImportNode',
    label: 'Import from URL',
    category: 'helper',
    color: '#8B7250',
    description: 'Paste a website link to pull its readable text + cover image into the canvas.',
    simpleExplanation: 'Paste any article or landing page link. Grabs the page text and cover image so you can turn it into carousels, prompts, or scripts.',
    inputs: [],
    outputs: ['text', 'image'],
  },
  {
    type: 'carouselBoardNode',
    label: 'Carousel Board',
    category: 'image',
    color: '#00c896',
    description: 'Turns text into a ready-to-post social carousel (hook, points, CTA slides).',
    simpleExplanation: 'Wire in page text (or paste your own) and it writes + renders a full carousel: hook slide, point slides, CTA slide. Crisp 1080×1350 PNGs, free to render, click to download.',
    inputs: ['text'],
    outputs: ['image'],
  },

  // ── UPLOAD (sources) ───────────────────────────────────────
  {
    type: 'imageUploadNode',
    label: 'Upload Image',
    category: 'helper',
    color: '#8B7250',
    description: 'Pick an image file from your computer to use as input.',
    simpleExplanation: 'Click to choose an image from your computer. It becomes the starting point for any image-based workflow.',
    inputs: [],
    outputs: ['image'],
  },
  {
    type: 'videoUploadNode',
    label: 'Upload Video',
    category: 'helper',
    color: '#8B7250',
    description: 'Pick a video file from your computer to use as input.',
    simpleExplanation: 'Click to choose a video file (mp4, mov, webm). Feed it into Video → Video, Lip Sync, or other video tools.',
    inputs: [],
    outputs: ['video'],
  },
  {
    type: 'audioUploadNode',
    label: 'Upload Audio',
    category: 'helper',
    color: '#8B7250',
    description: 'Pick an audio file from your computer to use as input.',
    simpleExplanation: 'Click to choose an audio file (mp3, wav). Feed it into Lip Sync or Speech → Video.',
    inputs: [],
    outputs: ['audio'],
  },

  // ── HELPERS ────────────────────────────────────────────────
  {
    type: 'compareNode',
    label: 'Compare',
    category: 'helper',
    color: '#fb923c',
    description: 'Shows two images side by side for comparison.',
    simpleExplanation: '👁️ Put two images side by side with a draggable slider to compare them. Perfect for seeing before/after: original vs upscaled, original vs relit, etc.',
    inputs: ['image', 'image'],
    outputs: [],
  },
  {
    type: 'stickyNoteNode',
    label: 'Sticky Note',
    category: 'helper',
    color: '#fb923c',
    description: 'A note you can leave on the canvas.',
    simpleExplanation: '📝 Just a note! Write reminders, labels or instructions for yourself right on the canvas. Great for organizing complex workflows so you remember what each part does.',
    inputs: [],
    outputs: [],
  },
  {
    type: 'iteratorNode',
    label: 'Iterator',
    category: 'helper',
    color: '#fb923c',
    description: 'Runs a node multiple times with different inputs.',
    simpleExplanation: '🔁 Run the same process on a whole bunch of images at once! Instead of generating 10 images one by one, set up an Iterator and it does them all automatically in a batch.',
    inputs: ['any'],
    outputs: ['any'],
  },

  // ── 3D (Meshy / Figma Weave style) ─────────────────────────
  {
    type: 'imageTo3DNode',
    label: 'Image → 3D',
    category: 'edit',
    color: '#5C9FCC',
    description: 'Turn an image or prompt into an interactive 3D mesh you can rotate.',
    simpleExplanation: 'Give it a photo or a prompt and it builds a 3D model. Drag to rotate, change the camera angle, then export the rendered shot as an image.',
    inputs: ['image', 'text'],
    outputs: ['image'],
  },

  // ── OUTPUT ─────────────────────────────────────────────────
  {
    type: 'outputNode',
    label: 'Output',
    category: 'output',
    color: '#fbbf24',
    description: 'Displays and downloads your final result.',
    simpleExplanation: '💾 This is the finish line! Connect any image or video here to preview and download your final creation. Every workflow should end here!',
    inputs: ['image', 'video'],
    outputs: [],
  },
]
